on:
  pull_request:
    branches:
      - "*"
name: check
jobs:
  site-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1
      - run: git lfs checkout
      - uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
