on:
  push:
    branches:
      - main
name: Publish docs
concurrency:
  group: "pages"
  cancel-in-progress: true
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1
      - run: git lfs checkout
      - uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "build"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
